apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: brief-ns
spec:
  selector:
    app: brief-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
